sudo: false
language: php
php:
  - hhvm
  - nightly
  - 5.2
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
before_script:
  - mv src/function src/a
script: 
  - sh travis-ci.sh src
after_script:
  - cat myerrorfile
